### ISSUE TITLE
New completion script for zsh

### ISSUE THREAD

**Issue by camfrout** [fishtown-analytics/dbt-completion.bash#6]
Hi!

I just came across the bash completion script, and while I am using zsh myself, the current script worked to auto-complete the models, with 2 caveats:

1. I had to update it to make it work with folders including spaces
2. Prefixing with '+' and '@' didn't work and was throwing errors

So, after spending a bit of time understanding zsh completion mechanism I have created the following script:
[Gist link](https://gist.github.com/camfrout/308ef4677af30eb39ec834fadefd32ce)

-- 

**Installation**
- If you are using Oh My Zsh, just save the _dbt file in ~/.oh-my-zsh/completions (create the folder if it doesn't exist)
- The script has been tested on macOS and with zsh version 5.8

**Pros**:
- Completion for models works with strings in the middle of the model names (e.g. typing `invoice` will match models `customer_invoice` and `vendor_invoice`
- Completion has been set up for some flags and commands (listing most of the flags available when running `dbt run`, `dbt test` and `dbt docs` as well as the global flags)
- Support for '+' and '@' has been replicated from the bash completion script

**Cons**:
- Currently, when running `dbt run` or `dbt test` the models will be suggested even though there is no model selection flag defined or if the model selection flag is not the last one in the list

-- 

Happy to submit a PR and share the script on this repo if people want to use it and improve it.

**Comment by jtcohen6** [comment]
Hey @camfrout, a PR for this would be most welcome!

**Comment by jtcohen6** [comment]
Resolved by #7
